language: julia
os:
    - linux
julia:
    - release
notifications:
    email: false
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'Pkg.clone(pwd()); Pkg.build("Turf"); Pkg.test("Turf"; coverage=true)'
after_success:
    - julia -e 'cd(Pkg.dir("Turf")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
